-- 코드를 입력하세요
SELECT A.YEAR, A.MONTH, A.PURCHASED_USERS, ROUND(A.PURCHASED_USERS/C.PURCHASED_PER_MONTH, 1) AS PUCHASED_RATIO
FROM(
        SELECT B.YEAR, B.MONTH, COUNT(DISTINCT B.USER_ID) AS PURCHASED_USERS
        FROM(
            SELECT O.USER_ID, EXTRACT(YEAR FROM SALES_DATE) AS YEAR, EXTRACT(MONTH FROM SALES_DATE) AS MONTH
            FROM ONLINE_SALE O RIGHT JOIN USER_INFO I ON O.USER_ID = I.USER_ID
            WHERE EXTRACT(YEAR FROM I.JOINED) = 2021
            ) B
        GROUP BY B.YEAR, B.MONTH
        HAVING YEAR IS NOT NULL
    ) A,
    (
        SELECT COUNT(USER_ID) AS PURCHASED_PER_MONTH
        FROM USER_INFO
        WHERE EXTRACT(YEAR FROM JOINED) = 2021
    ) C