-- 코드를 입력하세요
SELECT B.FLAVOR
FROM (
    SELECT A.FLAVOR, SUM(A.TOTAL_ORDER) AS TOTAL_ORDER
    FROM(
        SELECT * FROM FIRST_HALF C
        UNION
        SELECT * FROM JULY D
    ) A
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER DESC
) B
WHERE ROWNUM <=3